using System;

namespace BookEffectV3.Definitions
{
    // <Auto-Generated>
    // This is here so CodeMaid doesn't reorganize this document
    // </Auto-Generated>

    [Serializable]
    public class BookDefinition
    {
        public float Width = 1.1f;
        public float Height = 1.55f;
        public float Thickness = 0.2f;
        public float CoverThickness = 0.014f;
        public bool Hardback = true;
    }
}